export default Object.freeze({
  COMMENT_CREATE: "COMMENT_CREATE",
  COMMENT_UPDATE: "COMMENT_UPDATE",
  COMMENT_DELETE: "COMMENT_DELETE",
  FETCH_COMMENTS_REQUEST: "FETCH_COMMENTS_REQUEST",
  FETCH_COMMENTS_SUCCESS: "FETCH_COMMENTS_SUCCESS",
  FETCH_COMMENTS_FAILURE: "FETCH_COMMENTS_FAILURE",
});
